=== MyNextID/credentials/certificate-of-participation-in-summer-school/input-fields/input-fields-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Certificate of Participation in Summer School",
    "type": "object",
    "properties": {
        "credentialTitle":{
            "title":  "Credential title",
            "description": "Credential title to display on frontend",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                "type": "string",
                "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        },"fullName":{
            "title":"Full name",
            "description": "",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                "type": "string",
                "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        },"dateOfBirth": {
            "title": "Date of birth",
            "description": "",
            "type": "string",
            "format": "date-time"
        }, "placeOfBirth":{
            "title": "Country of birth",
            "description": "",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                "type": "string",
                "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        },"fullAddress":{
            "title": "City of birth",
            "description": "",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                "type": "string",
                "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        }, "studentNumber":{
            "title": "Student number",
            "description": "",
            "type": "string"
        },"academicYear":{
            "title": "Academic Year",
            "description": "",
            "type": "string"
        }, "programmeTitle":{
            "title": "Programme Title",
            "description": "",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                "type": "string",
                "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        },"workload": {
            "title":"Duration in hours",
            "description": "",
            "type": "string",
            "format": "duration"
        }, "validUntil":{
            "title": "Valid until",
            "description": "Date the certificate becomes expired.",
            "type": "string",
            "format": "date-time"
        }
    }, "required": [
        "credentialTitle",
        "programmeTitle",
        "placeOfBirth",
        "fullAddress"
    ]
}

=== MyNextID/credentials/certificate-of-participation-in-summer-school/input-fields/input-fields-example.json
{
    "credentialTitle":{
        "en":  "Certificate of Participation in Summer School"
    },"fullName":{
        "en":"John Doe"
    },"dateOfBirth":"1990-01-01T00:00:00Z",
    "placeOfBirth":{
        "en": "Slovenia"
    },"fullAddress":{
        "en": "A Great Address 2, 2025 Spicetown"
    }, "studentNumber":"12-345-678",
    "academicYear":"2026",
    "programmeTitle":{
        "en": "Mechanical Engineering"
    },"workload": "PT60H", 
    "validUntil":"2030-01-01T00:00:00Z"
}
