=== MyNextID/credentials/certificate-of-attendance/input-fields/input-fields-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Certificate of Attendance Schema",
    "type": "object",
    "properties": {
        "credentialTitle":{
            "title": "Credential title",
            "description": "The full name of the recipient of this credential",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                    "type": "string",
                    "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        }, "fullName" : {
            "title": "Full name",
            "description": "The full name of the recipient of this credential",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                    "type": "string",
                    "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        }, "achievementTitle":{
            "title": "Achievement title",
            "description": "A mapping of language codes to string values.",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                    "type": "string",
                    "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        },"achievementDescription":{
            "title": "Achievement description",
            "description": "A mapping of language codes to string values.",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                    "type": "string",
                    "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        }, "country":{
            "title": "Country",
            "description": "A mapping of language codes to string values.",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                    "type": "string",
                    "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        }, "address":{
            "title": "Address",
            "description": "A mapping of language codes to string values.",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                    "type": "string",
                    "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        }, "location":{
            "title": "Location",
            "description": "A mapping of language codes to string values.",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                    "type": "string",
                    "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        }, "url":{
            "title": "Website",
            "description": "The URL of the web resource.",
            "type": "string",
            "format": "uri"
        }, "endDate":{
            "title": "End Date",
            "description": "",
            "type": "string",
            "format": "date-time"
        }, "startDate":{
            "title": "Start Date",
            "description": "",
            "type": "string",
            "format": "date-time"
        }, "workload": {
            "title": "Duration in hours",
            "description": "",
            "type": "string",
            "format": "duration"
        }, "awardingStatement":{
            "title": "Awarding statement",
            "description": "A mapping of language codes to string values.",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                    "type": "string",
                    "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        }
    },
    "required": [
        "credentialTitle",
        "achievementTitle",
        "country",
        "address",
        "url"
    ]
}

=== MyNextID/credentials/certificate-of-attendance/input-fields/input-fields-example.json
{
    "credentialTitle":{
        "en": "Certificate of Attendance"
    }, "fullName" : {
        "en": "John Doe"
    }, "achievementTitle":{
        "en": "Title of your Conference"
    },"achievementDescription":{
        "en": "Here you should describe the activity of the event for which the recipient is receiving the Certificate of Attendance."
    }, "country":{
        "en": "Slovenia"
    }, "address":{
        "en": "A Great Address 2, 2025 Spicetown"
    }, "location":{
        "en": "Conference center"
    }, "url": "https://www.example.com",
    "startDate": "2026-01-01T00:00:00Z",
    "endDate":"2026-02-01T00:00:00Z", 
    "workload":"PT60H",
    "awardingStatement":{
        "en": "is awarded to"
    }
}
